### ISSUE TITLE
未定义变量 v:t_string

### ISSUE THREAD

**Issue by kingwen0302** [luzhlon/popup.vim#1]
在vim7.3没法使用,提示"未定义变量 v:t_string"
建议参考 https://github.com/Shougo/unite.vim/blob/master/autoload/vital/_unite/Prelude.vim

**Comment by luzhlon** [comment]
我会抽时间修正一下。 同时问一下，为什么不用高版本的vim呢？

**Comment by luzhlon** [comment]
建议升级到vim8.0版本以上，我不打算兼容旧版本的Vim了
