### ISSUE TITLE
Can't Not Work in linux wtih vim 8.1

### ISSUE THREAD

**Issue by yinflying** [luzhlon/popup.vim#2]
Unknown function: popup#add

Undefined variable: g:popup

Invalid expresssion: g:popup.ftmenus

Sad..

**Comment by luzhlon** [comment]
Please see the last document, APIs is changed.

**Comment by yinflying** [comment]
@luzhlon  I don't know which vim you are using.  I found some code in `popup.vim `:
```vim
let g:popup.menus = {}
let g:popup.ftmenus = {}
let g:popup.last = ['', '']
```
I don't think there is `struct` feature with vim variable. Here is error message. 
```
Undefined variable: g:popup
```

**Comment by luzhlon** [comment]
Yeah, `g:popup` is inited in `plugin/popup.vim` in older version.
Now, I moved it to `autoload/popup.vim`.

**Comment by luzhlon** [comment]
Update to the latest version, and try again. Thank you for using.

**Comment by yinflying** [comment]
It works, thank you for your working!
