### ISSUE TITLE
Feature request: Multiple Key Support

### ISSUE THREAD

**Issue by yinflying** [luzhlon/popup.vim#3]
Popup.vim now can only accept one as first index. I know multi-level index could make nearly identical function. However, Sometimes we don't need to show function with multi-level index. for example: 
```
['nt!', 'New tabpage', 'tabe'],
```
which accepts `nt` as hotkey to new a tab page.

In addition, `<F1>` to `<F12` also can not use as hotkey either.

**Comment by luzhlon** [comment]
I'm not going to support this feature. But you can use multi-level menu. For example:

    ['n:', 'New ...', [
      \ ['t', 'Tabpage', 'tabe'],
      \ ['b', 'Buffer', 'ene'],
      \ ]]

**Comment by yinflying** [comment]
Ok ,  I add `F1` to `F12` key support myself.
